@startuml

[*] -> p1_1: /-
p1_1 --> p1_2: V1::inTRp1_1_6/-
p2_1 --> p2_2: /V1::outTRp2_1_5 
p3_1 --> p3_2: V1::inTRp3_1_8/-
p2_3 --> p1_1: V1::inTRp2_1_2/-
p2_2 --> p2_3: /V1::outTRp2_1_4 
p1_2 --> p2_1: /V1::outTRp1_1_0 
p1_2 --> p3_1: /V1::outTRp1_1_1 
p3_3 --> p3_4: V1::inTRp3_3_9/-
p3_2 --> p3_3: /V1::outTRp3_1_7 
p3_4 --> p1_1: V1::inTRp3_1_3/-

@enduml
