@startuml

[*] -> p1_1
p1_1 --> p2_1: /V2::outTRp1_1_1
p1_1 --> p3_1: /V2::outTRp1_1_2
p1_2 --> p1_3: V2::inTRp1_2_8/-
p2_1 --> p2_2: /V2::outTRp2_1_9
p3_1 --> p1_2: V2::inTRp3_1_4/-
p4_1 --> p1_3: /V2::outTRp4_1_7
p1_3 --> p1_1: V2::inTRp1_3_5/-
p1_3 --> p4_1: V2::inTRp1_3_6/-
p2_2 --> p1_2: V2::inTRp2_1_3/-

@enduml
